---
title: "Figure S3C: TETON Cells / GRP78"
author: "Sandra Vidak"
date: "November 4th 2022"
output: github_document
---

```{r load-packages}
library(ggplot2)
library(ggthemes)
```

```{r set-knitr-options, include=FALSE}
knitr::opts_chunk$set(
  fig.path = 'output/',
  message = FALSE,
  warning = FALSE
  )
```

### Read Data for Fig S5D

Import and filter data and calculate sum and mean of the GRP78 peripheral recruitment for each biological replicate in TetON fibroblasts.

```{r}
GRP78_ring_1 <- read.csv(file="input/GRP78ring1.csv") 
GRP78_ring_1_filtered <- GRP78_ring_1 [ c(seq(1, nrow(GRP78_ring_1),4)), c("Intensity.Nucleus.3", "Intensity.Nucleus.4")]

GRP78_ring_1_filtered_rowsum <- rowSums(GRP78_ring_1_filtered[,1:2])

Mean_Uninduced_GRP78_1 <- mean(GRP78_ring_1_filtered_rowsum[1:3])

Mean_Induced_4days_GRP78_1 <- mean(GRP78_ring_1_filtered_rowsum[7:9])

```

```{r}
GRP78_ring_2 <- read.csv(file="input/GRP78ring1.csv") 

GRP78_ring_2_filtered <- GRP78_ring_2 [ c(seq(3, nrow(GRP78_ring_2),4)), c("Intensity.Nucleus.3", "Intensity.Nucleus.4")]

GRP78_ring_2_filtered_rowsum <- rowSums(GRP78_ring_2_filtered[,1:2])

Mean_Uninduced_GRP78_2 <- mean(GRP78_ring_2_filtered_rowsum[1:3])

Mean_Induced_4days_GRP78_2 <- mean(GRP78_ring_2_filtered_rowsum[7:9])
```

```{r}
GRP78_ring_3 <- read.csv(file="input/GRP78ring2.csv") 

GRP78_ring_3_filtered <- GRP78_ring_3 [ c(seq(1, nrow(GRP78_ring_3),4)), c("Intensity.Nucleus.3", "Intensity.Nucleus.4")]

GRP78_ring_3_filtered_rowsum <- rowSums(GRP78_ring_3_filtered[,1:2])

Mean_Uninduced_GRP78_3 <- mean(GRP78_ring_3_filtered_rowsum[1:3])

Mean_Induced_4days_GRP78_3 <- mean(GRP78_ring_3_filtered_rowsum[7:9])
```

```{r}
GRP78_Uninduced <- c(Mean_Uninduced_GRP78_1, Mean_Uninduced_GRP78_2, Mean_Uninduced_GRP78_3)

GRP78_Induced4days <- c(Mean_Induced_4days_GRP78_1, Mean_Induced_4days_GRP78_2, Mean_Induced_4days_GRP78_3)

GRP78_df <- data.frame (GRP78_Uninduced,GRP78_Induced4days)
rownames(GRP78_df) <- c("Biological replicate1", "Biological replicate2", "Biological replicate3")

```

Calculate mean and SD for 3 different biological replicates in every condition

```{r}
Mean_GRP78_levels <- apply (GRP78_df,2,mean)

SD_GRP78_levels <- apply (GRP78_df,2,sd)

Mean_GRP78_levels2 <- as.data.frame(Mean_GRP78_levels)

SD_GRP78_levels2 <- as.data.frame(SD_GRP78_levels)
Condition <- rep(c("GFP-LA OFF","GFP-LA ON"), each=1)
GRP78_plot <- data.frame(Mean_GRP78_levels2,SD_GRP78_levels2, Condition )
```

### Biological Replicates Level plot for Fig.S5D

```{r Fig_S3C, echo=FALSE}
ggplot(GRP78_plot, aes(x = Condition, y = Mean_GRP78_levels,
                       ymin = Mean_GRP78_levels-SD_GRP78_levels, 
                       ymax = Mean_GRP78_levels+SD_GRP78_levels)) + 
  geom_crossbar()+
  ylab("Intensity") + 
  ggtitle("GRP78ring")  +
  scale_y_continuous(expand = c(0, 0), limits = c(0,8000))

```

Document the information about the analysis session

```{r sessionInfo, include=TRUE, echo=TRUE, results='markup'}
sessionInfo()
```
